apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PersistentVolumeClaim.name}}
spec:
  storageClassName: {{ .Values.PersistentVolumeClaim.storageclassname}}
  accessModes:
    - {{ .Values.PersistentVolumeClaim.accessModes}}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.resources.requests.storage}}
